import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { decidePermission, DEFAULT_PERMISSION_RULES, isLegacyAutoAddedRuleSet, mergePermissionRules, trustLevelToMode } from '../src/ai-permission-rules.ts';

const commandHandler = {
  requiresConfirm: (args: { command: string }) => /\brm\s+-|\bsudo\b/.test(args.command),
  isDestructive: () => false,
} as any;

function decision(command: string) {
  return decidePermission('run_command', { command }, commandHandler, trustLevelToMode(1), DEFAULT_PERMISSION_RULES);
}

test('semi-auto restores the legacy command heuristic for non-dangerous commands', () => {
  for (const command of ['pwd', 'ls -lah', 'git status --short', 'echo hello', 'cat secrets.txt', 'curl example.com', 'pwd; echo hi']) {
    assert.deepEqual(decision(command), { kind: 'allow' }, command);
  }
});

test('semi-auto still asks for dangerous commands', () => {
  for (const command of ['sudo id', 'rm -rf tmp', 'pwd; rm -rf tmp']) {
    assert.deepEqual(decision(command), { kind: 'ask' }, command);
  }
});

test('explicit permission rules still take precedence over semi-auto defaults', () => {
  assert.deepEqual(decidePermission('run_command', { command: 'pwd' }, commandHandler, 'acceptSafe', [
    { tool: 'run_command', match: { command: '^pwd$' }, action: 'ask' },
  ]), { kind: 'ask' });
  assert.deepEqual(decidePermission('run_command', { command: 'pwd' }, {
    ...commandHandler, requiresConfirm: () => true,
  }, 'acceptSafe', []), { kind: 'ask' });
  assert.deepEqual(decidePermission('run_command', { command: 'pwd' }, commandHandler, 'ask', []), { kind: 'ask' });
});

test('custom permission rules keep defaults active without displaying them as custom rows', () => {
  const rules = mergePermissionRules([{ tool: 'run_command', match: { command: '^pwd$' }, action: 'ask' }]);
  assert.deepEqual(decidePermission('run_command', { command: 'pwd' }, commandHandler, 'acceptSafe', rules), { kind: 'ask' });
  assert.equal(decidePermission('run_command', { command: 'git reset --hard' }, commandHandler, 'acceptAll', rules).kind, 'deny');
});

test('only the exact rule set generated by the old Add button is recognized for cleanup', () => {
  const generated = [...DEFAULT_PERMISSION_RULES, { tool: 'run_command', action: 'ask' as const }];
  assert.equal(isLegacyAutoAddedRuleSet(generated), true);
  assert.equal(isLegacyAutoAddedRuleSet([...generated, { tool: 'read_file', action: 'allow' }]), false);
  assert.equal(isLegacyAutoAddedRuleSet([{ ...generated[0], action: 'allow' }, ...generated.slice(1)]), false);
  assert.equal(mergePermissionRules(generated).some(rule => rule.tool === 'run_command' && !rule.match), false);
});

test('loading settings removes the exact auto-added rule set from persisted settings', () => {
  const file = readFileSync(new URL('../src/themes.ts', import.meta.url), 'utf8');
  const source = ts.createSourceFile('themes.ts', file, ts.ScriptTarget.Latest, true);
  const fn = source.statements.find((node): node is ts.FunctionDeclaration =>
    ts.isFunctionDeclaration(node) && node.name?.text === 'loadSettings');
  assert.ok(fn);
  const code = ts.transpileModule(fn.getText(source).replace(/^export\s+/, ''), {
    compilerOptions: { target: ts.ScriptTarget.ES2021, module: ts.ModuleKind.CommonJS },
  }).outputText;
  const generated = [...DEFAULT_PERMISSION_RULES, { tool: 'run_command', action: 'ask' }];
  let saved: Record<string, unknown> | undefined;
  const load = new Function('localStorage', 'SETTINGS_KEY', 'DEFAULT_SETTINGS', 'applySettingsSecrets',
    'saveSettings', 'isLegacyAutoAddedRuleSet', `${code}\nreturn loadSettings;`)(
    { getItem: () => JSON.stringify({ aiPermissionRules: generated }) },
    'settings',
    { aiProviders: [] },
    (settings: unknown) => settings,
    (settings: Record<string, unknown>) => { saved = settings; },
    isLegacyAutoAddedRuleSet,
  );
  assert.equal(load().aiPermissionRules, undefined);
  assert.equal(saved?.aiPermissionRules, undefined);
});
